version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ai-aggregator-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  redis:
    image: redis:latest
    container_name: ai-aggregator-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api-gateway:
    build:
      context: ./api-gateway
    container_name: ai-aggregator-api-gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongodb:27017/ai-aggregator?authSource=admin
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./api-gateway:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: ai-aggregator-frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway
    environment:
      - NODE_ENV=development
      - API_URL=http://api-gateway:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
  redis_data: